import Head from "next/head";
import styles from "@/styles/Home.module.css";

export default function Layout({ children }) {
  return (
    <>
      <Head>
        <title>Dulces Pétalos</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <header className={styles.header}>
          <h1 className={styles.headerText}>Dulces Pétalos</h1>
        </header>
        <div>{children}</div>
        <footer className={styles.footer}>
          <p className={styles.footerText}>Copyright ©</p>
        </footer>
      </main>
    </>
  );
}
