import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "@/styles/Home.module.css";

export default function Layout({ children }) {
  return (
    <>
      <Head>
        <title>Dulces Pétalos</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <header className={styles.header}>
          <Link className={styles.headerContent} href="/">
            <Image
              className={styles.logo}
              src="/logo.png"
              width={40}
              height={40}
            />
            <h1 className={styles.headerText}>Dulces Pétalos</h1>
          </Link>
        </header>
        <div className={styles.childrenContainer}>{children}</div>
        <footer className={styles.footer}>
          <p className={styles.footerText}>Copyright ©</p>
        </footer>
      </main>
    </>
  );
}
